server:
  servlet:
    context-path: /driver-service
  port: 8080

spring:
  application:
    name: driver-service

  #  configure jdbc driver and datasource
  data:
    cassandra:
      keyspace-name: driver_ks
      contact-points: localhost
      port: 9042
      schema-action: CREATE
      base-packages: com.ridemanagement.driverservice

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka


#logging
logging:
  level:
    org:
      springframework:
        security: TRACE
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# encryption key
encryptor:
  initialization-vector: "sampleSampleSamp"

#cors
cors:
  allowedOrigin: ${UI_URL}